# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojotrust', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
