# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojotrust', '0002_auto_20190605_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('real', 'Real Estate'), ('cars', 'Automobile'), ('agri', 'Agriculture'), ('wear', 'Clothes')], default='select', max_length=7),
        ),
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, default='user.png', upload_to='business/'),
        ),
    ]
