# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojotrust', '0004_auto_20190605_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.CharField(blank=True, help_text='Leave a review', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.ImageField(blank=True, default='user.png', upload_to='profile/'),
        ),
    ]
